---
title: "Spatial Data Basics"
output: html_notebook
---
* Dante Christopher-Alphonso <dantealphonso@gmail.com>

## Libraries
```{r}
# Loading packages for being able to manipulate and plot spatial data
library(tidyverse)
library(sf)
library(ggplot2)
```

## Data
```{r}
# Reading in the Former Municipality Boundaries Data GeoJson file and reprojecting
fmbd <- st_read('data/Former Municipality Boundaries Data.geojson') %>% st_transform(3857)

# Reading in the Community Shelters shapefile and reprojecting
shelters <- st_read("data/Shelter/shelters_wgs84.shp") %>% st_transform(3857)

# Reading in the Waste GeoJson File and reprojecting
waste <- st_read("data/waste.geojson") %>% st_transform(3857)

# Reading in the City Wards Data GeoJson File and reprojecting
cwd <- st_read("data/City Wards Data.geojson") %>% st_transform(3857)
``` 

## Functions
### Buffer and spatial join function
```{r}
#'Buffers geodataframe 1 and joins it to the nearest geometries in geodataframe 2.
#'
#'@param gdf1 A geodataframe with points.
#'@param gdf2 A geodataframe with polygons.
#'@param dist Buffer distance to apply. Default is 1000.
#'
#'@return The geodataframe after applying a buffer to gdf1 and joining to geometries of gdf2.
buffer_sjoin <- function(gdf1, gdf2, dist = 1000){
  
  # Buffer gdf1 by dist
  gdf1_buff <- st_buffer(gdf1, dist)
  
  # Join the geometries of gdf2 with buffered gdf1
  result <- st_join(gdf1_buff, gdf2)
  return(result)
}
```

### Spatial join and count function
```{r}
#'Takes geodataframe 1 and joins it to the geometries in geodataframe 2, then counts the number of points from      geodataframe 1.
#'
#'@param gdf1 A geodataframe with points.
#'@param gdf2 A geodataframe with polygons.
#'
#'@return The geodataframe after joining gdf1 and gdf2 and counting the number of points from gdf1.
sjoin_count <- function(gdf1, gdf2){
  
  # Join the geometries of gdf1 with gdf2
  sjoin_gdf1_gdf2 <- st_join(gdf1, gdf2, how="inner", predicate="within")
  
  point_count <- sjoin_gdf1_gdf2 %>% group_by(polygon_id) %>% summarise(point_count = n())
  
  return(point_count)
}
```


### Buffer_sjoin demo
Demo
```{r}
# Join shelters and fmbd together after buffering shelters
# Note the default distance is 1000, but it can be changed
# e.g. buffer_sjoin(shelters, fmbd, dist = 100) for a 100 meter buffer
buffer_sjoin_shelters_fmbd <- buffer_sjoin(shelters, fmbd)
```

Display non-spatial data
```{r}
# Showing non-spatial results of buffer_sjoin
buffer_sjoin_shelters_fmbd
```

Display spatial data
```{r}
# Spatially plot the results of the buffer_sjoin function
plot(st_geometry(buffer_sjoin_shelters_fmbd))
```

### Sjoin_count demo
Demo
```{r}
# Counting points from waste after joining it to cwd
sjoin_count_waste_cwd <- sjoin_count(waste, cwd)
```

Display non-spatial data
```{r}
# Showing non-spatial results of sjoin_count
sjoin_count_waste_cwd
```

Display spatial data
```{r}
# Spatially plot the results of the sjoin_count function
plot(st_geometry(sjoin_count_waste_cwd))
```